# -*- mode: dockerfile -*-
# dockerfile to build libmxnet.so
FROM ubuntu:18.04

# COPY install/sources-16.04.list install/
# RUN rm /etc/apt/sources.list && \
#     cp install/sources-16.04.list /etc/apt/sources.list && \
#     rm -r /etc/apt/sources.list.d && \
#     apt-get update

COPY docker/install/pip.sh install/
RUN install/pip.sh

COPY docker/install/cpp.sh install/
RUN install/cpp.sh

ENV BUILD_OPTS "USE_DIST_KVSTORE=1"
