# -*- mode: dockerfile -*-
# dockerfile to build libmxnet.so on GPU
FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

# COPY install/sources-16.04.list install/
# RUN rm /etc/apt/sources.list && \
#     cp install/sources-16.04.list /etc/apt/sources.list && \
#     rm -r /etc/apt/sources.list.d && \
#     apt-get update

COPY install/pip.sh install/
RUN install/pip.sh

COPY install/cpp.sh install/
RUN install/cpp.sh

ENV BUILD_OPTS "USE_DIST_KVSTORE=1"
